# 10 Estimate the Estate

## Your Objective

Your dataset contains property sales for one-family dwellings in Manhattan over the last 12 months, including each property's zip code, building class, square feet, and sale price. However, records have have a sale price of $0 whenever there was a transfer of ownership without a cash consideration (like from parents to children).

Your task is create a new market value column that uses the recorded sale price when available, or estimates it by using the average price per square foot from properties within the same zip code and building class.

See example below:

![image](../images/jrolA7H60U64I7hDhRwEAnIQ.avif)

_BONUS: Can you impute by scraping the real market values from the internet based on each address?_

In [6]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/manhattan_property_sales.csv')
df.head()

,NEIGHBORHOOD,ADDRESS,ZIP_CODE,BUILDING_CLASS,SQUARE_FEET,SALE_PRICE
0,CHELSEA,150 WEST 15TH STREET,10011,A4,8997,14999999
1,CHELSEA,348 WEST 22 STREET,10011,A4,3042,13500000
2,CHELSEA,204 WEST 21ST STREET,10011,A4,3365,7650000
3,CHELSEA,481 WEST 22 STREET,10011,A4,3666,0
4,CHELSEA,344 W 22 STREET,10011,A4,4395,13100000

In [3]:
df['PRICE_PER_SQFT'] = df['SALE_PRICE'] / df['SQUARE_FEET']
df.head()

,NEIGHBORHOOD,ADDRESS,ZIP_CODE,BUILDING_CLASS,SQUARE_FEET,SALE_PRICE,PRICE_PER_SQFT
0,CHELSEA,150 WEST 15TH STREET,10011,A4,8997,14999999,1667.222296
1,CHELSEA,348 WEST 22 STREET,10011,A4,3042,13500000,4437.869822
2,CHELSEA,204 WEST 21ST STREET,10011,A4,3365,7650000,2273.402675
3,CHELSEA,481 WEST 22 STREET,10011,A4,3666,0,0.000000
4,CHELSEA,344 W 22 STREET,10011,A4,4395,13100000,2980.659841

In [4]:
df['AVG_PRICE_PER_SQFT'] = df.groupby(['ZIP_CODE', 'BUILDING_CLASS'])['PRICE_PER_SQFT'].transform('mean')
df.head()

,NEIGHBORHOOD,ADDRESS,ZIP_CODE,BUILDING_CLASS,SQUARE_FEET,SALE_PRICE,PRICE_PER_SQFT,AVG_PRICE_PER_SQFT
0,CHELSEA,150 WEST 15TH STREET,10011,A4,8997,14999999,1667.222296,2075.324328
1,CHELSEA,348 WEST 22 STREET,10011,A4,3042,13500000,4437.869822,2075.324328
2,CHELSEA,204 WEST 21ST STREET,10011,A4,3365,7650000,2273.402675,2075.324328
3,CHELSEA,481 WEST 22 STREET,10011,A4,3666,0,0.000000,2075.324328
4,CHELSEA,344 W 22 STREET,10011,A4,4395,13100000,2980.659841,2075.324328

In [7]:
df['MARKET_VALUE'] = np.where(df['SALE_PRICE'] > 0, df['SALE_PRICE'], df['AVG_PRICE_PER_SQFT'] * df['SQUARE_FEET'])
df.head()

,NEIGHBORHOOD,ADDRESS,ZIP_CODE,BUILDING_CLASS,SQUARE_FEET,SALE_PRICE,PRICE_PER_SQFT,AVG_PRICE_PER_SQFT,MARKET_VALUE
0,CHELSEA,150 WEST 15TH STREET,10011,A4,8997,14999999,1667.222296,2075.324328,1.500000e+07
1,CHELSEA,348 WEST 22 STREET,10011,A4,3042,13500000,4437.869822,2075.324328,1.350000e+07
2,CHELSEA,204 WEST 21ST STREET,10011,A4,3365,7650000,2273.402675,2075.324328,7.650000e+06
3,CHELSEA,481 WEST 22 STREET,10011,A4,3666,0,0.000000,2075.324328,7.608139e+06
4,CHELSEA,344 W 22 STREET,10011,A4,4395,13100000,2980.659841,2075.324328,1.310000e+07

In [8]:
sum(df['MARKET_VALUE'] > 15000000)

19