# 07 Turning Bullish

## Your Objective

Your dataset for this drill contains daily closing prices for the SPDR S&P 500 ETF Trust (SPY) over the last 5 years.

Your task is to calculate the 50-day and 200-day moving averages based on the closing price, and identify every “Golden Cross” moment – when the short-term average (50-day) crosses from below to above the long-term average (200-day) – signaling a potential bull market.

![image](../images/5H9l4utlcOBL5kkzNdxEvqA.avif)

To complete the drill, create a table containing the date, close price, and three new columns:

1. 50-day moving average: The average closing price for the last 50 trading days, calculated for each date
2. 200-day moving average: The average closing price for the last 200 trading days, calculated for each date
3. Golden Cross: A binary field (1/0) that equals 1 only on the exact date when the 50-day average crosses from below the 200-day average; otherwise 0

![image](../images/T3csxYZQayr0beVSf7Aigj1x7gM.avif)

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data/SPY_close_price_5Y.csv', parse_dates=['Date'])

df.head()

        Date   Close
0 2020-11-02  330.20
1 2020-11-03  336.03
2 2020-11-04  343.54
3 2020-11-05  350.24
4 2020-11-06  350.16

In [9]:
df.assign(
    mean_50_day = lambda x: x["Close"].rolling(window=50, min_periods=50).mean(),
    mean_200_day = lambda x: x["Close"].rolling(window=200, min_periods=200).mean(),
    golden_cross = lambda x: ((x.mean_50_day > x.mean_200_day) & (x.mean_50_day.shift(1) <= x.mean_200_day.shift(1))).astype(int)
).query('golden_cross == 1').sort_values('Date', ascending=False).head(10)

           Date   Close  mean_50_day  mean_200_day  golden_cross
1169 2025-07-01  617.65     583.0978     582.04155             1
566  2023-02-02  416.78     394.3504     394.25025             1

In [8]:
df.head()

        Date   Close
0 2020-11-02  330.20
1 2020-11-03  336.03
2 2020-11-04  343.54
3 2020-11-05  350.24
4 2020-11-06  350.16