# 06 Streak Leaderboard

## Your Objective
You work for a popular language learning company and have a table containing ~900,000 lesson completions, including the date, user, and lesson ID.

Your task is to calculate the active streak for each user, then create a leaderboard of the top 10 users with the longest active streaks.

- The streak length is the number of consecutive days with at least one lesson completion
- For the purpose of this drill, consider the current date to be 2025-09-29
- For a streak to be considered “active”, the user must have completed a lesson on 2025-09-28

 See example below:

![image](../images/aFGnHBJX6Oqc0O2NjLXveh42f4.avif)

In [1]:
import pandas as pd

lessons = (
    pd.read_csv('data/LessonStreaks.csv', parse_dates=['date'])
    .drop_duplicates(subset=['user_id', 'date'])
    .sort_values(['user_id', 'date'])
)

lessons.head()

             id  lesson_id       date  user_id    user_name
9330    7839783   63658156 2025-05-01  8226413  Aeris Stone
41178   7872349   63658157 2025-05-05  8226413  Aeris Stone
45072   7876346   63658171 2025-05-06  8226413  Aeris Stone
51344   7882741   63658176 2025-05-07  8226413  Aeris Stone
123456  7956420   64983797 2025-05-21  8226413  Aeris Stone

In [2]:
lessons["streak"] = lessons.groupby('user_id', as_index=False)["date"].diff().ne(pd.Timedelta(days=1)).cumsum()

lessons.head()

             id  lesson_id       date  user_id    user_name  streak
9330    7839783   63658156 2025-05-01  8226413  Aeris Stone       1
41178   7872349   63658157 2025-05-05  8226413  Aeris Stone       2
45072   7876346   63658171 2025-05-06  8226413  Aeris Stone       2
51344   7882741   63658176 2025-05-07  8226413  Aeris Stone       2
123456  7956420   64983797 2025-05-21  8226413  Aeris Stone       3

In [3]:
streaks = lessons.groupby(["user_id", "user_name", "streak"]).agg(
    streak_len = ("date", "count"), 
    start = ("date", "min"),
    end = ("date", "max")
).reset_index()

In [4]:
streaks.head()

   user_id    user_name  streak  streak_len      start        end
0  8226413  Aeris Stone       1           1 2025-05-01 2025-05-01
1  8226413  Aeris Stone       2           3 2025-05-05 2025-05-07
2  8226413  Aeris Stone       3           3 2025-05-21 2025-05-23
3  8226413  Aeris Stone       4           2 2025-05-28 2025-05-29
4  8226413  Aeris Stone       5           3 2025-06-03 2025-06-05

In [5]:
active_date = pd.to_datetime("2025-09-28")

streaks.query('end >= @active_date').sort_values('streak_len', ascending=False).head(10)

         user_id           user_name  streak  streak_len      start        end
2419    84071240        Stan Pancake    2420         151 2025-05-01 2025-09-28
32      16814590        Tom Parmesan      33         121 2025-05-31 2025-09-28
14987  215518363     Chuck Butternut   14988         120 2025-06-01 2025-09-28
14074  213142099         Helen Melon   14075          96 2025-06-25 2025-09-28
14739  215121049    Gertrude Strudel   14740          88 2025-07-03 2025-09-28
4567   176891675       Scott Pockett    4568          78 2025-07-13 2025-09-28
31446  227438241   Demetrius Trumpet   31447          76 2025-07-15 2025-09-28
8661   199107800      Shrimp Pringle    8662          53 2025-08-07 2025-09-28
12520  210092431  Skeeter Weaselwood   12521          51 2025-08-09 2025-09-28
1785    74627365         Hal Halibut    1786          49 2025-08-11 2025-09-28