# 09 The Price is Right

## Your Objective

Your dataset contains three tables from a pizza restaurant:

1. A transactions table with order date, product, and quantity
2. A products table with the current price for each product
3. A price history table with the price changes for each product over time

Your task is to look up the price for each product in the transactions table at that point in time, accurately reflecting the price changes.

NOTE: If the effective date of a price change is equal to the order date for a transaction, then that is the price that should be reflected.

See example below:

![image](../images/ShnCDNAcigFpLy8IKWGLTufQo0.avif)

In [1]:
import pandas as pd

price_history = pd.read_csv('data/price_history.csv', parse_dates=['effective_date'])
price_history.head()

   pizza_id effective_date  price
0         1     2026-01-01  20.75
1         2     2026-01-01  17.95
2         3     2026-01-01  20.75
3         4     2026-01-01  16.50
4         5     2026-01-01  20.25

In [2]:
transactions = pd.read_csv('data/transactions.csv', parse_dates=['order_date'])
transactions.head()

   order_detail_id  order_id order_date  pizza_id  quantity
0                1         1 2026-01-01         4         1
1                2         2 2026-01-01         6         1
2                3         2 2026-01-01         2         1
3                4         2 2026-01-01         9         1
4                5         2 2026-01-01        10         1

In [13]:
transactions_total = pd.merge_asof(
    transactions, 
    price_history, 
    left_on='order_date', 
    right_on='effective_date',
    by='pizza_id'
).assign(line_total = lambda x: x.price * x.quantity).groupby('order_id').agg({'line_total': 'sum'}).reset_index().rename(columns={'line_total': 'transaction_total'})

transactions_total.head()

   order_id  transaction_total
0         1              16.50
1         2              97.20
2         3              41.50
3         4              20.75
4         5              20.75

In [14]:
transactions_total["transaction_total"].sum()

np.float64(161144.35)